### ISSUE TITLE
SVG <use> tag support

### ISSUE THREAD

**Issue by abdo-spices** [cxa/astro-inline-svg#1]
SVG <use> tag support like astro-icon but when the icon is the first one and not repetitive not to use tag

**Comment by cxa** [comment]
Could you provide an use case?

**Comment by abdo-spices** [comment]
> Could you provide an use case?

Yes, here in fruit ui 
https://fruit-ui.vercel.app/docs/getting-started/overview
![image](https://github.com/user-attachments/assets/0d14c036-0865-4393-ad49-d281c01b9181)
this arrows if don't know is same svg and using <use> tag

it's not hard to get 30 of them of more

**Comment by cxa** [comment]
Thanks. Supported since 0.4.0.

**Comment by abdo-spices** [comment]
thank you you saved me 
https://github.com/spices-solutions/wathqny/pull/26
