### ISSUE TITLE
Error running astro build

### ISSUE THREAD

**Issue by rtpm** [cxa/astro-inline-svg#2]
Hello, 
Not sure where the problem relies, but disabling / removing the package and not using it causes astro build problems:

> (0 , css_select_1.selectOne) 

is not a function 

which is caused by node-html-parser

Using it via component Svg:

```
---
import Svg from "@cxa/astro-inline-svg";

const props  = Astro.props;
import Icon from '@assets/images/icon.svg?raw';
---

<Svg raw={Icon} {...props} />
```

**Comment by cxa** [comment]
Sorry, as you described, I don't see any problem is caused by `astro-inline-svg`. Remove it and reinstall your `node_modules` when in any doubt.

**Comment by rtpm** [comment]
Will do, thanks for quick check and response.

Just to clarify.
The problem was with `Image` component from `astro:assets`.

```
10:03:05 ▶ src/pages/about.astro
10:03:05   └─ /about/index.html(0 , css_select_1.selectOne) is not a function
  Stack trace:
    at HTMLElement.querySelector (file:///Users/robert/dev/public_website/dist/chunks/logoC_D-z0NNqY.mjs:2580:43)
```
    
Removing the package fixed the problem. Will leave it here as it may not be related to your package directly as `css_select_1.selectOne` is used in node-html-parser.
